### ISSUE TITLE
Is it possible to add Capacities Constraints to this problem?

### ISSUE THREAD

**Issue by bilics** [jmarca/tsp_multiple_days#1]
Hello! Thanks for such thorough explanation about this code on your blog! I am just starting with or-tools and it helped immensely!

On to the question: is it possible to add another type of constraint to this problem, namely "capacities constraints", as in the example 
[CVPR](https://developers.google.com/optimization/routing/cvrp)?

The idea is to have multiple vehicles, demands at each node and capacities for each vehicle.

Thanks in advance,

**Comment by jmarca** [comment]
Yes of course

Almost all of the work I do with or-tools involves pickup and delivery of some sort (which requires tracking capacities, demands, etc). The question didn’t ask that however, and often simple is better when explaining a concept. 

And we’re always available for hire if you have a complicated situation you want modeled. 

James

**Comment by bilics** [comment]
Thanks, we might need that in the future - we are trying to validate a possible solution first. But for now I am trying to understand if (and how) to do that. The email for a possible quote is the one in the blog activimetrics.com ?

Regarding the problem I understand it would be a matter of adding a `AddDimensionWithVehicleCapacity` in addition of all other restrictions - is this the path?

Thanks again

**Comment by jmarca** [comment]
Yes dimensions are used to track accumulating things. Each additional dimension adds complexity of course, but you can use them to restrict the solution space to what you want…pickups before deliveries, respecting vehicle capacity, etc. 

James

**Comment by bilics** [comment]
Thanks James! I am investigating in this direction.
