### ISSUE TITLE
magic numbers

### ISSUE THREAD

**Issue by jacobjove** [jmarca/tsp_multiple_days#2]
First, thanks for the example!

I see a bunch of `2`s in here. Should that be `args.days` or `num_days*2` or something?

*Edit*: It seems `2` represents the number of morning and night nodes included in the original matrix; i.e., since the original matrix in this example includes the start node and the end node (but not the dummy nodes), `2` is used to adjust the number of dummy nodes that need to be created/used.

**Comment by jacobjove** [comment]
One more thing: I'm confused by the naming of `num_days`. `num_days` is set to `args.days - 1`. Could you please explain why? 

*Edit*: It appears that `num_days` actually represents the number of dummy morning nodes and dummy night nodes to create, and it's equal to `args.days - 1` because the matrix already includes the start node (which is a morning node) and the end node (which is a night node).

**Comment by jmarca** [comment]
This is a scratch project as an example.

Feel free to use is as a way to learn.  But I am not going to respond to issues.
